export const jdJobs = [
  {
    id: 1,
    title: "Senior UI/UX Designer",
    company: "Amazon",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/4/4a/Amazon_icon.svg",
    colorCard: "peach",
    postedDate: "20 May, 2026",
    posted: "2 days ago",
    location: "San Francisco, CA",
    workMode: "Remote",
    salary: "$250/hr",
    salaryNum: 2500,
    payPeriod: "hr",
    type: "Part-Time",
    schedule: "Part time",
    employmentType: "Flexible schedule",
    experienceLevel: "Senior level",
    industry: "Design",
    deadline: "Oct 15, 2026",
    duration: "1 year",
    match: 98,
    matchBreakdown: { skills: 98, location: 95, experience: 100, workMode: 100 },
    tags: ["Part time", "Senior level", "Distant", "Project work"],
    description:
      "Amazon is looking for a Senior UI/UX Designer to craft next-generation commerce and cloud experiences with modern interaction standards.",
    requirements: [
      "5+ years of experience in product & interaction design",
      "Mastery of Figma, design systems, and user research",
      "Demonstrated ability to simplify complex workflows",
      "Strong portfolio showcasing shipped digital products",
    ],
  },
  {
    id: 2,
    title: "Junior UI/UX Designer",
    company: "Google",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg",
    colorCard: "mint",
    postedDate: "4 Feb, 2026",
    posted: "1 week ago",
    location: "California, CA",
    workMode: "Hybrid",
    salary: "$150/hr",
    salaryNum: 1800,
    payPeriod: "hr",
    type: "Full-time",
    schedule: "Full time",
    employmentType: "Flexible schedule",
    experienceLevel: "Junior level",
    industry: "Design",
    deadline: "Sep 30, 2026",
    duration: "Full-time",
    match: 94,
    matchBreakdown: { skills: 95, location: 90, experience: 88, workMode: 95 },
    tags: ["Full time", "Junior level", "Distant", "Project work", "Flexible Schedule"],
    description:
      "Join the Google design team to build accessible, delightfully simple user experiences across Google Search and Workspace tools.",
    requirements: [
      "1-2 years experience or strong design portfolio",
      "Proficiency in Figma and interactive prototyping",
      "Deep empathy for universal accessibility and user testing",
      "Collaborative mindset with cross-functional engineering teams",
    ],
  },
  {
    id: 3,
    title: "Senior Motion Designer",
    company: "Dribbble",
    companyLogo: "https://cdn.iconscout.com/icon/free/png-256/free-dribbble-logo-icon-download-in-svg-png-gif-file-formats--social-media-pack-logos-icons-2902888.png?f=webp&w=256",
    colorCard: "lavender",
    postedDate: "29 Jan, 2026",
    posted: "3 days ago",
    location: "New York, NY",
    workMode: "Remote",
    salary: "$260/hr",
    salaryNum: 2600,
    payPeriod: "hr",
    type: "Part-Time",
    schedule: "Part time",
    employmentType: "Shift work",
    experienceLevel: "Senior level",
    industry: "Design",
    deadline: "Sep 28, 2026",
    duration: "6 months",
    match: 92,
    matchBreakdown: { skills: 94, location: 85, experience: 92, workMode: 98 },
    tags: ["Part time", "Senior level", "Full Day", "Shift work"],
    description:
      "Dribbble is seeking a Senior Motion Designer to lead our visual animation, micro-interactions, and high-impact brand campaigns.",
    requirements: [
      "5+ years of motion graphics and UI micro-interaction expertise",
      "Mastery of After Effects, Lottie, Rive, and Figma",
      "Exceptional eye for timing, easing, and spatial dynamics",
      "Portfolio with brand and product motion reels",
    ],
  },
  {
    id: 4,
    title: "UX Designer",
    company: "Twitter",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Logo_of_Twitter.svg",
    colorCard: "sky",
    postedDate: "11 Apr, 2026",
    posted: "4 days ago",
    location: "California, CA",
    workMode: "Remote",
    salary: "$120/hr",
    salaryNum: 1400,
    payPeriod: "hr",
    type: "Full-time",
    schedule: "Full time",
    employmentType: "Full day",
    experienceLevel: "Middle level",
    industry: "Design",
    deadline: "Oct 10, 2026",
    duration: "Full-time",
    match: 90,
    matchBreakdown: { skills: 90, location: 92, experience: 88, workMode: 90 },
    tags: ["Full time", "Middle level", "Distant", "Project work"],
    description:
      "Help shape conversation and connection for millions of users worldwide as a UX Designer focusing on creator tools and real-time feeds.",
    requirements: [
      "3+ years experience with high-scale web and mobile apps",
      "Solid understanding of information architecture and user flows",
      "Ability to rapid prototype and test hypotheses quickly",
      "Passion for social communication and community platforms",
    ],
  },
  {
    id: 5,
    title: "Graphic Designer",
    company: "Airbnb",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg",
    colorCard: "pink",
    postedDate: "2 Apr, 2026",
    posted: "5 days ago",
    location: "San Francisco, CA",
    workMode: "Hybrid",
    salary: "$300/hr",
    salaryNum: 3000,
    payPeriod: "hr",
    type: "Part-Time",
    schedule: "Part time",
    employmentType: "Flexible schedule",
    experienceLevel: "Senior level",
    industry: "Design",
    deadline: "Sep 20, 2026",
    duration: "1 year",
    match: 89,
    matchBreakdown: { skills: 92, location: 90, experience: 85, workMode: 86 },
    tags: ["Part time", "Senior level", "Distant", "Flexible Schedule"],
    description:
      "Craft bespoke visual narratives and campaign design for Airbnb's global community of hosts and travelers.",
    requirements: [
      "Stunning graphic design portfolio covering branding and digital media",
      "Excellence in typography, color theory, and layout",
      "Experience partnering with creative directors and copywriters",
      "Proficiency in Adobe Creative Cloud and Figma",
    ],
  },
  {
    id: 6,
    title: "Graphic Designer",
    company: "Apple",
    companyLogo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    colorCard: "lilac",
    postedDate: "18 Jan, 2026",
    posted: "1 week ago",
    location: "San Francisco, CA",
    workMode: "Hybrid",
    salary: "$140/hr",
    salaryNum: 1600,
    payPeriod: "hr",
    type: "Part-Time",
    schedule: "Part time",
    employmentType: "Shift work",
    experienceLevel: "Middle level",
    industry: "Design",
    deadline: "Sep 25, 2026",
    duration: "Full-time",
    match: 95,
    matchBreakdown: { skills: 96, location: 95, experience: 90, workMode: 94 },
    tags: ["Part time", "Distant", "Flexible Schedule", "Shift work"],
    description:
      "Join Apple's design group to craft iconic visual assets, marketing layouts, and keynote presentation designs with obsessive precision.",
    requirements: [
      "Obsessive attention to craft, typography, and detail",
      "Strong portfolio demonstrating high aesthetic standards",
      "Proficiency in Figma, Illustrator, and Photoshop",
      "Ability to thrive in a fast-paced, collaborative design environment",
    ],
  },
  {
    id: 7,
    title: "Frontend Developer Intern",
    company: "Nexora Studio",
    companyLogo: "/logo-nexora.webp",
    colorCard: "peach",
    postedDate: "24 Aug, 2026",
    posted: "3 days ago",
    location: "Jakarta, ID",
    workMode: "Hybrid",
    salary: "$800/mo",
    salaryNum: 800,
    payPeriod: "mo",
    type: "Internship",
    schedule: "Internship",
    employmentType: "Flexible schedule",
    experienceLevel: "Intern",
    industry: "Technology",
    deadline: "Sep 12, 2026",
    duration: "6 months",
    match: 96,
    matchBreakdown: { skills: 94, location: 98, experience: 90, workMode: 100 },
    tags: ["Internship", "Junior level", "Hybrid", "Project work"],
    description:
      "Join Nexora Studio as a Frontend Developer Intern. You will work alongside senior engineers building responsive, accessible interfaces for our job platform and employer tools.",
    requirements: [
      "Familiarity with HTML, CSS, and JavaScript",
      "Basic knowledge of React or other component frameworks",
      "Good eye for pixel-perfect, design-system-consistent UI",
      "Portfolio or mini-project demonstrating frontend work",
    ],
  },
  {
    id: 8,
    title: "Backend Engineer (Junior)",
    company: "Nexora Cloud",
    companyLogo: "/logo-nexora.webp",
    colorCard: "mint",
    postedDate: "15 Aug, 2026",
    posted: "5 days ago",
    location: "Bandung, ID",
    workMode: "Remote",
    salary: "$1,100/mo",
    salaryNum: 1100,
    payPeriod: "mo",
    type: "Entry Level",
    schedule: "Full time",
    employmentType: "Distant work",
    experienceLevel: "Junior level",
    industry: "Technology",
    deadline: "Sep 20, 2026",
    duration: "Full-time",
    match: 91,
    matchBreakdown: { skills: 92, location: 95, experience: 88, workMode: 90 },
    tags: ["Full time", "Junior level", "Distant", "Full Day"],
    description:
      "Build REST APIs, database schemas, and microservices with mentorship from senior backend architects at Nexora Cloud.",
    requirements: [
      "Understanding of Node.js, Express, and PostgreSQL",
      "Knowledge of authentication principles and secure API design",
      "Familiarity with Git version control",
      "Eager to learn high-throughput distributed systems",
    ],
  },
];

export function formatJobTags(job) {
  return job.tags || [job.location, job.workMode, job.salary, job.posted];
}

export function jobById(id) {
  return jdJobs.find((j) => String(j.id) === String(id));
}

export function daysLeft(deadline) {
  const end = new Date(deadline);
  if (Number.isNaN(end.getTime())) return 999;
  return Math.ceil((end - Date.now()) / 86400000);
}