export const jdJobs = [
  {
    id: 1,
    title: "Frontend Developer Intern",
    company: "Nexora Studio",
    tags: ["Jakarta", "Hybrid", "$800/mo", "3 days ago"],
    location: "Jakarta",
    workMode: "Hybrid",
    salary: "$800/mo",
    type: "Internship",
    industry: "Technology",
    posted: "3 days ago",
    deadline: "Sep 12, 2026",
    duration: "6 months",
    match: 96,
    matchBreakdown: { skills: 94, location: 98, experience: 90, workMode: 100 },
    description:
      "Join Nexora Studio as a Frontend Developer Intern. You will work alongside senior engineers building responsive, accessible interfaces for our job platform and employer tools.",
    requirements: [
      "Familiarity with HTML, CSS, and JavaScript",
      "Basic knowledge of React or other component frameworks",
      "Good eye for pixel-perfect, design-system-consistent UI",
      "Portfolio or mini-project demonstrating frontend work",
    ],
  },
  {
    id: 2,
    title: "UI/UX Designer Grad",
    company: "Brightmind Agency",
    tags: ["Bandung", "On-site", "$950/mo", "1 week ago"],
    location: "Bandung",
    workMode: "On-site",
    salary: "$950/mo",
    type: "Entry Level",
    industry: "Design",
    posted: "1 week ago",
    deadline: "Sep 5, 2026",
    duration: "1 year",
    match: 88,
    matchBreakdown: { skills: 92, location: 80, experience: 85, workMode: 95 },
    description:
      "Brightmind Agency is looking for a recent graduate UI/UX designer to turn research into polished, high-fidelity interfaces for our product clients.",
    requirements: [
      "Degree or bootcamp in design-related field",
      "Portfolio with mobile and web case studies",
      "Proficiency in Figma",
      "Basic understanding of usability testing",
    ],
  },
  {
    id: 3,
    title: "Data Analyst (Entry)",
    company: "CloudNine Analytics",
    tags: ["Remote", "Flexible", "$1.1k/mo", "5 days ago"],
    location: "Jakarta",
    workMode: "Remote",
    salary: "$1.1k/mo",
    type: "Entry Level",
    industry: "Data & Analytics",
    posted: "5 days ago",
    deadline: "Sep 20, 2026",
    duration: "Full-time",
    match: 74,
    matchBreakdown: { skills: 70, location: 100, experience: 68, workMode: 60 },
    description:
      "CloudNine builds analytics products for SME clients. We are hiring a junior analyst to clean data, build reports, and turn numbers into readable insights.",
    requirements: [
      "Working knowledge of SQL and spreadsheets",
      "Familiarity with a BI tool (Looker Studio, Tableau, or Power BI)",
      "Strong attention to detail",
      "Willingness to learn Python basics",
    ],
  },
  {
    id: 4,
    title: "Marketing Assistant",
    company: "Vertex Retail",
    tags: ["Surabaya", "Hybrid", "$700/mo", "2 days ago"],
    location: "Surabaya",
    workMode: "Hybrid",
    salary: "$700/mo",
    type: "Entry Level",
    industry: "Marketing",
    posted: "2 days ago",
    deadline: "Sep 8, 2026",
    duration: "Full-time",
    match: 81,
    matchBreakdown: { skills: 78, location: 84, experience: 80, workMode: 82 },
    description:
      "Support the Vertex Retail marketing team across social media, content calendar, and campaign reporting. Great first step into brand marketing.",
    requirements: [
      "Interest in social media and content creation",
      "Decent writing skills in English",
      "Comfort with Google Workspace",
      "Organized and proactive",
    ],
  },
  {
    id: 5,
    title: "Backend Developer Intern",
    company: "Nexora Studio",
    tags: ["Jakarta", "Remote", "$850/mo", "4 days ago"],
    location: "Jakarta",
    workMode: "Remote",
    salary: "$850/mo",
    type: "Internship",
    industry: "Technology",
    posted: "4 days ago",
    deadline: "Sep 15, 2026",
    duration: "6 months",
    match: 69,
    matchBreakdown: { skills: 72, location: 100, experience: 62, workMode: 60 },
    description:
      "Build REST APIs, database schemas, and internal tooling with mentorship from our senior backend team.",
    requirements: [
      "Some experience with Node.js or Go",
      "Understanding of SQL databases",
      "Familiarity with Git and REST principles",
      "Curiosity about cloud platforms",
    ],
  },
  {
    id: 6,
    title: "Product Manager (Junior)",
    company: "Lumen Labs",
    tags: ["Jakarta", "Hybrid", "$1.3k/mo", "1 week ago"],
    location: "Jakarta",
    workMode: "Hybrid",
    salary: "$1.3k/mo",
    type: "Entry Level",
    industry: "Technology",
    posted: "1 week ago",
    deadline: "Sep 25, 2026",
    duration: "Full-time",
    match: 91,
    matchBreakdown: { skills: 88, location: 95, experience: 90, workMode: 92 },
    description:
      "Own small product pods end-to-end: collect feedback, write specs, and coordinate delivery with design and engineering.",
    requirements: [
      "Strong communication and writing skills",
      "Analytical mindset, comfortable with metrics",
      "Ability to run discovery interviews",
      "Experience with agile rituals is a plus",
    ],
  },
  {
    id: 7,
    title: "Social Media Specialist (Freelance)",
    company: "Coffee & Co.",
    tags: ["Remote", "Part-Time", "$500/mo", "6 days ago"],
    location: "Bandung",
    workMode: "Remote",
    salary: "$500/mo",
    type: "Freelance",
    industry: "Marketing",
    posted: "6 days ago",
    deadline: "Sep 3, 2026",
    duration: "3 months",
    match: 58,
    matchBreakdown: { skills: 55, location: 100, experience: 54, workMode: 50 },
    description:
      "Plan and schedule content for Coffee & Co.'s Instagram and TikTok, craft captions, and monitor engagement.",
    requirements: [
      "Portfolio of social media content",
      "Comfortable with design tools like Canva or Figma",
      "Reliable and responsive",
      "Basic video editing skills",
    ],
  },
  {
    id: 8,
    title: "QA Tester (Entry)",
    company: "PayGate Fintech",
    tags: ["Jakarta", "On-site", "$900/mo", "1 day ago"],
    location: "Jakarta",
    workMode: "On-site",
    salary: "$900/mo",
    type: "Entry Level",
    industry: "Fintech",
    posted: "1 day ago",
    deadline: "Sep 10, 2026",
    duration: "Full-time",
    match: 77,
    matchBreakdown: { skills: 76, location: 88, experience: 72, workMode: 70 },
    description:
      "Join our QA squad to write test cases, run regression cycles, and keep our payment flows rock solid.",
    requirements: [
      "Attention to detail and patience for repetitive test runs",
      "Basic understanding of web apps",
      "Analytical debugging mindset",
      "ISTQB foundation is a nice-to-have",
    ],
  },
  {
    id: 9,
    title: "HR Assistant (Part-Time)",
    company: "Makmur Group",
    tags: ["Semarang", "Hybrid", "$600/mo", "2 weeks ago"],
    location: "Semarang",
    workMode: "Hybrid",
    salary: "$600/mo",
    type: "Part-Time",
    industry: "Corporate",
    posted: "2 weeks ago",
    deadline: "Sep 18, 2026",
    duration: "6 months",
    match: 63,
    matchBreakdown: { skills: 60, location: 75, experience: 65, workMode: 55 },
    description:
      "Support recruitment scheduling, onboarding paperwork, and employee engagement initiatives at Makmur Group.",
    requirements: [
      "Good interpersonal and organizational skills",
      "Proficient in spreadsheets",
      "Ability to handle confidential information",
      "Previous admin experience is a plus",
    ],
  },
  {
    id: 10,
    title: "Graphic Designer Intern",
    company: "Studio Arang",
    tags: ["Yogyakarta", "Hybrid", "$450/mo", "2 days ago"],
    location: "Yogyakarta",
    workMode: "Hybrid",
    salary: "$450/mo",
    type: "Internship",
    industry: "Design",
    posted: "2 days ago",
    deadline: "Sep 22, 2026",
    duration: "4 months",
    match: 84,
    matchBreakdown: { skills: 86, location: 78, experience: 82, workMode: 88 },
    description:
      "Create social assets, posters, and brand mockups for local and international clients at a fun, small studio.",
    requirements: [
      "Strong portfolio of design work",
      "Proficiency in Figma and Photoshop",
      "Typography and layout fundamentals",
      "Willingness to iterate fast",
    ],
  },
];

export function formatJobTags(job) {
  return [job.location, job.workMode, job.salary, job.posted];
}

export function jobById(id) {
  return jdJobs.find((j) => String(j.id) === String(id));
}

export function daysLeft(deadline) {
  const end = new Date(deadline);
  if (Number.isNaN(end.getTime())) return 999;
  return Math.ceil((end - Date.now()) / 86400000);
}